# Prometheus configuration for Inventory Management API

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Inventory Management API
  - job_name: 'inventory-api'
    static_configs:
      - targets: ['inventory-api:8081']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker containers (if Docker metrics enabled)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
