# Prometheus configuration for Inventory Management API

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'local-docker'
    environment: 'development'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector metrics endpoint
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Inventory Management API (direct scraping)
  - job_name: 'inventory-api-direct'
    static_configs:
      - targets: ['inventory-management-system:9080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Store S1 API (if it has metrics)
  - job_name: 'store-s1-api'
    static_configs:
      - targets: ['store-s1:9080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # OpenTelemetry Collector internal metrics
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: '/metrics'
    scrape_interval: 30s
